name: Sync

on: workflow_dispatch

jobs:
  sync:
    name: Sync from swsnr/keep-me-awake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: "curl -sSfL https://codeberg.org/swsnr/keep-me-awake/raw/branch/main/flatpak/de.swsnr.keepmeawake.yaml > de.swsnr.keepmeawake.yaml"
      - run: "curl -sSfL https://codeberg.org/swsnr/keep-me-awake/raw/branch/main/flatpak/de.swsnr.keepmeawake.cargo-sources.json > de.swsnr.keepmeawake.cargo-sources.json"
      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update from swsnr/keep-me-awake"
          branch: swsnr/keep-me-awake/update
          delete-branch: true
          base: master
          sign-commits: true
          title: Update manifest from upstream
          body: |
            Update flatpak manifest from [swsnr/keep-me-awake](https://codeberg.org/swsnr/keep-me-awake).

            PR created by [sync workflow](https://github.com/flathub/de.swsnr.keepmeawake/actions/workflows/sync.yaml)
          assignees: swsnr
